language: julia
os: 
  - linux

julia:
  - 1.0
  - nightly

script: 
  - julia -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'

codecov: true
coveralls: true

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
